server:
  context-path: /
  port: 8080

---

spring:
  profiles: dev
  database:
    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:h2:~/cloud_computing;MV_STORE=FALSE;MVCC=FALSE
    username: sa
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate: 
      ddl-auto: create
    show-sql: true
    
jsondoc:
  version: 1.0
  basePath: http://localhost:8080/
  packages: 
    - com.computing.cloud.controller
    - com.computing.cloud.domain
    - com.computing.cloud.to.request
    - com.computing.cloud.to.response

---
 
spring: 
  profiles: test
  database:
    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:h2:~/cloud_computing_test;MV_STORE=FALSE;MVCC=FALSE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
---

spring:
  profiles:
    active: dev